export enum ServiceResultErrorType {
  NotFound = 0,
  IDataModelStorageService_EmptyName = 1,
  IDataModelStorageService_InvalidName = 2,
  IDataModelStorageService_DuplicateName = 3,
  IDataModelStorageService_NameTooLong = 4,
  IDataModelStorageService_ParentNotFound = 5,
  IDataModelStorageService_DuplicateBookmark = 6,
  IDataModelStorageService_InvalidBookmark = 7,
  IDataModelStorageService_Insert_DuplicateDataModelEntity = 8,
  IDataModelStorageService_Insert_DuplicateTypeInstance = 9,
  IDataModelStorageService_Insert_MissingRequiredFieldInstance = 10,
  IDataModelStorageService_Update_TypeInstanceIsInUseInLayout = 11,
  IDataModelStorageService_SaveScope_InvalidDataModel = 12,
  IDataModelStorageService_SaveScope_DataModelInUseInRelation = 13,
  IDataModelService_Save_ValidationFailed = 14,
  IDataModelService_Save_Bundle_InvalidDataModel = 15,
}
